apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: fluxcdbot@adhithia.me
        name: robot-fluxcd
      messageTemplate: 'ada update image baru: {{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
  update:
    path: ./main/production/namespaces
    strategy: Setters