apiVersion: v1
kind: Secret
metadata:
    name: payments
type: Opaque
data:
    payment-gatway.json: ENC[AES256_GCM,data:hIV84j8CV6f/m/8EHUbcVT4rXbgY7YnPgFoadp8HJQgqN8r1jizyJLzZ/0b1Ko3ry6mn+BlM+gZAwVdQjKvie+02X/8f7YzMCFjAVQxgv5OnLD05eKgJN00xXEd3etOdscivgXFqAU7jHlnQsscuJkXM1UZ8W0TW4U27Bs+erQ/tLT+apqCcL/hKbPpsJ2sUj4m1C5k=,iv:zoacfBUKiF6kyxMeSwimbhIWaAkgcQf+l8YM1BhEHxk=,tag:VYfcBtcnDkqylh1aOI/eGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l5ucv8qy0drc6jrxqv8tyl4x9s32z6uyc0uey7zme3sn9djvpffqnxveu9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NllBVjhoNHJ0dDVXKzc2
            UURJbjRBMGtqdzFhVS9kQTh4TEdZYlJlWmlzCjc1ZisrVXROZVNuWVhOYU9NVzB1
            eGdhWkl3N2RCWVNNSlg0R2ZMeDIwZDQKLS0tIGFMTldBcG8yOWZBajA0QjhRNDlz
            cGVadS9SV1IvUGEyUFZRY0pyTGttQmMK9RAlWj6rNbXri/z+AmLXe+ZFddCxPEmR
            McLeNNU2N7hCgwTrUsOTGYfB3sBh2GX7NPiG2HYJJtUFhdN9H+n0VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T13:48:33Z"
    mac: ENC[AES256_GCM,data:S2QPMwnttHKcBKDxflgbgbSuXo+caq+GxIb7RE2hFxR2S4BTrFxmWumt66x1VEnvM4OOcVqvECN4qzcUKYG227f9/dh68cIZApfxFAUkjzEKXdbJMli2wZwere0mXq5bcijKd8f8kIVGhdvAoObSm7MbDaG/p7J1SQOYWHTZLEs=,iv:6Udlpp+D2631JlexOiqKuGY1C/4NCtU3GYOn4Cxlfyo=,tag:0TNkw55M3ef/bivrDUFPbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
