apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: aditirvan/load-test:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: 60Mi
            cpu: 50m
        ports:
        - containerPort: 8080
