apiVersion: v1
kind: Secret
metadata:
    name: products
type: Opaque
data:
    admin: ENC[AES256_GCM,data:xjO+GL2Dgq0=,iv:8b7uvg8KJsl1dmlxhVuHpBp5dN/cz6MCZbzPTv5HEj0=,tag:zE5Fu4ykC9s4YgVIGvhK/g==,type:str]
    password: ENC[AES256_GCM,data:DHJaMePbflZhNeTuTbWJjg4w6NE=,iv:Ey+Ofu58PRlZUOjMY/twPkAnUZNn+3kTaIpPr3ZIyIE=,tag:tVdbTrcLlheL5fgFPJ2kiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l5ucv8qy0drc6jrxqv8tyl4x9s32z6uyc0uey7zme3sn9djvpffqnxveu9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVytQTVhJRzZlRE1NWWtJ
            TGVqdnkyRjhZalVXS2xxZHFxVmRtN2VyYkcwCjhPajhZck1LNmIyMk1kZFhYMGs5
            Qk5BWVJsVDdqeFlOblp2VzZQVG5KQ1UKLS0tIHR6Z05sTGkyTSs1RWVUNVIrV29a
            OTV4a1FPcGNBbTJrczRrTzhQckFEQ2MK+hH3JWdl9sLHaC4bP7K2Un0diq4aw2hk
            XvysMNQybMeb9M7mlJEnTkNvQxN+o2BSg5uXMhpTrpuJniD9XOvP3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T13:37:54Z"
    mac: ENC[AES256_GCM,data:fWXw4tC3uMAkrUJ7uMBfKFFbCqdQXPnV84xi2xRBE31dtDgMdqMSKZ5PQdk+WqPO4ZAJidaL3t9je0fxf0u79ryJ27pKc64dtIOJT6bYQh1c1azaBDlcJYwx+NrAPU9v9/aFyCJjenUFaK0GpGMYobc8TY40GJgkYz8hLcmP+b8=,iv:+ecGPkWIiridk/MZ1hZyh/uJHhTCMmzXzaIPsTmDLQo=,tag:BUPBclkUuFDPmNBQAym+bg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
